# Travis CI-test2 Configuration File

# Tell Travis CI we're using PHP
language: php

# Build matrix options bang
matrix:
  include:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

# Set default environment variables, multisite off and always against master branch of WP
env:
  - WP_VERSION=master WP_MULTISITE=0 WP_TRAVISCI=travis:phpunit

# Before install, failures in this section will result in build status 'errored'
before_install:
  - WP_CORE_DIR=/tmp/wordpress/
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cd tests
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php

# Script, failures in this section will result in build status 'failed'
script: "phpunit -c custom.xml.dist"
